---
dependencies: []

galaxy_info:
  author: dstoeckm
  description: CentOS RHEL Common
  company: "Cisco"
  license: "license (MIT)"
  min_ansible_version: 1.6
  platforms:
  - name: EL
    versions:
      - 5
      - 6
  categories:
    -
    -
    - 
